### ISSUE TITLE
BottomSheetScrollView doesn't work!

### ISSUE THREAD

**Issue by firasrg** [th3rdwave/react-navigation-bottom-sheet#19]
Hello!

I have a sheet view with a **scrollable list**. The scroll doesn't work! We've tried many ways to solve it but nothing works!
I've reproduced the issue [within a snack](https://snack.expo.dev/@iga-frg/bottomsheet-navigator-scroll-issue?platform=android)

Please Help !

**Comment by eduduardo** [comment]
To work properly you should use `ScrollView` from `react-native-gesture-handler`:

```
import { ScrollView } from 'react-native-gesture-handler';
```

**Comment by joseortiz9** [comment]
@eduduardo in this case we lose the possibility to close the BS with the scroll gesture, which is a feature of `BottomSheetScrollView`.

**Comment by muhammadarsal** [comment]
experiencing the same isssue

**Comment by firasrg** [comment]
@kamack38 do you have same issue ? try to update to recent version `0.3.1`

**Comment by firasrg** [comment]
@kamack38 you should use [BottomSheetScrollView](https://ui.gorhom.dev/components/bottom-sheet/components/bottomsheetscrollview/)

**Comment by kamack38** [comment]
Big thanks, now that I try it, it actually works.

If you wouldn't mind I have quick question for you. Do you know how can I "subscribe" to the current snapPoint change, or how can I get the current snap point?

**Comment by firasrg** [comment]
Oh great, that means this issue is solved ✅. If you want to follow the snappoints, I think you need to use the `snapToPosition()` api (check [documentation](https://ui.gorhom.dev/components/bottom-sheet/methods#snaptoposition))

**Comment by firasrg** [comment]
@kamack38  maybe [useBottomSheetDynamicSnappoints()](https://ui.gorhom.dev/components/bottom-sheet/hooks#usebottomsheetdynamicsnappoints)

**Comment by kamack38** [comment]
I think I was looking for `animatedIndex`, but thanks for the help nonetheless.

**Comment by swk-dean** [comment]
@firasrg How did u fix this? What exactly did u do? Can you add examples?

**Comment by visualcookie** [comment]
@firasrg How did u fix this? What exactly did u do? Can you add examples?

**Comment by firasrg** [comment]
Hello @visualcookie ! As i said in a [previous message](https://github.com/th3rdwave/react-navigation-bottom-sheet/issues/19#issuecomment-2302191478) and make sure your dependencies are updated.
